# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/triumph/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/motorola/triumph/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/motorola/triumph/proprietary/lib/libcamera.so:obj/lib/libcamera.so \

# Audio
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so

# BIN
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/bin/bluetoothd:system/bin/bluetoothd \
    vendor/motorola/triumph/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/motorola/triumph/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/motorola/triumph/proprietary/bin/wpdiagd:system/bin/wpdiagd \
    vendor/motorola/triumph/proprietary/bin/btwlancoex:system/bin/btwlancoex \
    vendor/motorola/triumph/proprietary/bin/cnd:system/bin/cnd \
    vendor/motorola/triumph/proprietary/bin/hostapd:/system/bin/hostapd \
    vendor/motorola/triumph/proprietary/bin/hostapd_cli:/system/bin/hostapd_cli \
    vendor/motorola/triumph/proprietary/bin/rmt_storage:/system/bin/rmt_storage \
    vendor/motorola/triumph/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/motorola/triumph/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init

# Camera
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/motorola/triumph/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/motorola/triumph/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/motorola/triumph/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/motorola/triumph/proprietary/lib/libmmipl.so:system/lib/libmmipl.so

# GPS files from Cherry 2.3.5
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/lib/libcommondefs.so:obj/lib/libcommondefs.so \
    vendor/motorola/triumph/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/motorola/triumph/proprietary/lib/libloc.so:system/lib/libloc.so \
    vendor/motorola/triumph/proprietary/lib/libloc_api.so:system/lib/libloc_api.so \
    vendor/motorola/triumph/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/motorola/triumph/proprietary/lib/libloc-rpc.so:system/lib/libloc-rpc.so


# OMX
#PRODUCT_COPY_FILES += \
#    vendor/motorola/triumph/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
#    vendor/motorola/triumph/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
#    vendor/motorola/triumph/proprietary/lib/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
#    vendor/motorola/triumph/proprietary/lib/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
#    vendor/motorola/triumph/proprietary/lib/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
#    vendor/motorola/triumph/proprietary/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
#    vendor/motorola/triumph/proprietary/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
#    vendor/motorola/triumph/proprietary/lib/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
#    vendor/motorola/triumph/proprietary/lib/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
#    vendor/motorola/triumph/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so

# RIL
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/bin/rild:system/bin/rild \
    vendor/motorola/triumph/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/motorola/triumph/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/motorola/triumph/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/motorola/triumph/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/motorola/triumph/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/motorola/triumph/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/motorola/triumph/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/motorola/triumph/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/motorola/triumph/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/motorola/triumph/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/motorola/triumph/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/motorola/triumph/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/motorola/triumph/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/motorola/triumph/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/motorola/triumph/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/motorola/triumph/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/motorola/triumph/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/motorola/triumph/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/motorola/triumph/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/motorola/triumph/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/motorola/triumph/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/motorola/triumph/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/motorola/triumph/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/motorola/triumph/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/motorola/triumph/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/motorola/triumph/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/motorola/triumph/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/motorola/triumph/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/motorola/triumph/proprietary/lib/libpdapi.so:system/lib/libpdapi.so \
    vendor/motorola/triumph/proprietary/lib/libpdsm_atl.so:system/lib/libpdsm_atl.so \
    vendor/motorola/triumph/proprietary/lib/libuim.so:system/lib/libuim.so

# Sensors binaries
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/motorola/triumph/proprietary/bin/lightd:system/bin/lightd \
    vendor/motorola/triumph/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/motorola/triumph/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/motorola/triumph/proprietary/bin/proximityd:system/bin/proximityd \
    vendor/motorola/triumph/proprietary/bin/thermald:system/bin/thermald \
    vendor/motorola/triumph/proprietary/lib/hw/sensors.qcom.so:/system/lib/hw/sensors.triumph.so

# Copyright (C) 2012 Qualcomm Developer Network
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Vendor extension library
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.extension_library=/system/lib/libqc-opt.so

# Prebuilt shared libraries
#PRODUCT_COPY_FILES += \
#    vendor/motorola/triumph/proprietary/lib/caf/libv8.so:obj/lib/libv8.so

# Prebuilt CodeAurora libraries
#PRODUCT_COPY_FILES += \
#    vendor/motorola/triumph/proprietary/lib/caf/libv8.so:system/lib/libv8.so \
#    vendor/motorola/triumph/proprietary/lib/caf/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
 #   vendor/motorola/triumph/proprietary/lib/caf/libmmosal.so:system/lib/libmmosal.so \
 #   vendor/motorola/triumph/proprietary/lib/caf/libmmparser.so:system/lib/libmmparser.so \
 #   vendor/motorola/triumph/proprietary/lib/caf/libmmparser_lite.so:system/lib/libmmparser_lite.so \
 #   vendor/motorola/triumph/proprietary/lib/caf/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
 #   vendor/motorola/triumph/proprietary/lib/caf/libDivxDrm.so:system/lib/libDivxDrm.so \
  #  vendor/motorola/triumph/proprietary/lib/caf/libqc-opt.so:system/lib/libqc-opt.so

# Prebuilt libraries for CAF Chromium plug-ins
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/lib/caf/libcneapiclient.so:/system/lib/libcneapiclient.so \
    vendor/motorola/triumph/proprietary/lib/caf/libcneqmiutils.so:/system/lib/libcneqmiutils.so \
    vendor/motorola/triumph/proprietary/lib/caf/libdiag.so:/system/lib/libdiag.so \
    vendor/motorola/triumph/proprietary/lib/caf/libdnshostprio.so:/system/lib/libdnshostprio.so \
    vendor/motorola/triumph/proprietary/lib/caf/libnetmonitor.so:/system/lib/libnetmonitor.so \
    vendor/motorola/triumph/proprietary/lib/caf/libtcpfinaggr.so:/system/lib/libtcpfinaggr.so \
    vendor/motorola/triumph/proprietary/lib/caf/pp_proc_plugin.so:/system/lib/pp_proc_plugin.so \
    vendor/motorola/triumph/proprietary/lib/caf/qnet-plugin.so:/system/lib/qnet-plugin.so \
    vendor/motorola/triumph/proprietary/lib/caf/tcp-connections.so:/system/lib/tcp-connections.so

# Prebuilt Adreno 2xx libraries
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/etc/firmware/a225_pfp.fw:/system/etc/firmware/a225_pfp.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/a225_pm4.fw:/system/etc/firmware/a225_pm4.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/a225p5_pm4.fw:/system/etc/firmware/a225p5_pm4.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/a300_pfp.fw:/system/etc/firmware/a300_pfp.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/a300_pm4.fw:/system/etc/firmware/a300_pm4.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/leia_pfp_470.fw:/system/etc/firmware/leia_pfp_470.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/leia_pm4_470.fw:/system/etc/firmware/leia_pm4_470.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/yamato_pfp.fw:/system/etc/firmware/yamato_pfp.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/yamato_pm4.fw:/system/etc/firmware/yamato_pm4.fw \
    vendor/motorola/triumph/proprietary/lib/egl/egl.cfg:/system/lib/egl/egl.cfg \
    vendor/motorola/triumph/proprietary/lib/egl/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/motorola/triumph/proprietary/lib/egl/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/motorola/triumph/proprietary/lib/egl/libGLES_android.so:/system/lib/egl/libGLES_android.so \
    vendor/motorola/triumph/proprietary/lib/egl/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/motorola/triumph/proprietary/lib/egl/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/motorola/triumph/proprietary/lib/egl/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/motorola/triumph/proprietary/lib/libC2D2.so:/system/lib/libC2D2.so \
    vendor/motorola/triumph/proprietary/lib/libgsl.so:/system/lib/libgsl.so \
    vendor/motorola/triumph/proprietary/lib/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/motorola/triumph/proprietary/lib/libsc-a2xx.so:/system/lib/libsc-a2xx.so

# Gsensor & Ecompass
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/app/ECompassCalibration.apk:/system/app/ECompassCalibration.apk \
    vendor/motorola/triumph/proprietary/app/GSensorCalibration.apk:/system/app/GSensorCalibration.apk

# Triumph init scripts
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/etc/vold.fstab:system/etc/vold.fstab \
    vendor/motorola/triumph/proprietary/etc/init.qcom.bt.sh:/system/etc/init.qcom.bt.sh \
    vendor/motorola/triumph/proprietary/etc/init.qcom.coex.sh:/system/etc/init.qcom.coex.sh\
    vendor/motorola/triumph/proprietary/etc/init.qcom.bt.sh:/system/etc/init.qcom.fm.sh \
    vendor/motorola/triumph/proprietary/etc/init.qcom.sdio.sf6.sh:/system/etc/init.qcom.sdio.sf6.sh \
    vendor/motorola/triumph/proprietary/etc/init.qcom.sdio.sh:/system/etc/init.qcom.sdio.sh \
    vendor/motorola/triumph/proprietary/etc/init.qcom.wifi.sh:/system/etc/init.qcom.wifi.sh \
    vendor/motorola/triumph/proprietary/etc/init.apn.sh:/system/etc/init.apn.sh \
    vendor/motorola/triumph/proprietary/etc/telephony.sql:/system/etc/telephony.sql 

# Keychars
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/usr/keychars/fih_headsethook.kcm.bin:system/usr/keychars/fih_headsethook.kcm.bin \
    vendor/motorola/triumph/proprietary/usr/keychars/fih_ringswitch.kcm.bin:system/usr/keychars/fih_ringswitch.kcm.bin \
    vendor/motorola/triumph/proprietary/usr/keychars/qwerty2.kcm.bin:system/usr/keychars/qwerty2.kcm.bin \
    vendor/motorola/triumph/proprietary/usr/keychars/qwerty.kcm.bin:system/usr/keychars/qwerty.kcm.bin \
    vendor/motorola/triumph/proprietary/usr/keychars/sf6_kybd.kcm.bin:system/usr/keychars/sf6_kybd.kcm.bin \
    vendor/motorola/triumph/proprietary/usr/keychars/sf8_kybd.kcm.bin:system/usr/keychars/sf8_kybd.kcm.bin \
    vendor/motorola/triumph/proprietary/usr/keychars/surf_keypad.kcm.bin:system/usr/keychars/surf_keypad.kcm.bin \
    vendor/motorola/triumph/proprietary/usr/keychars/surf_keypad_qwerty.kcm.bin:system/usr/keychars/surf_keypad_qwerty.kcm.bin \
    vendor/motorola/triumph/proprietary/usr/keychars/surf_keypad_numeric.kcm.bin:system/usr/keychars/surf_keypad_numeric.kcm.bin

# Keylayouts
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/usr/keylayout/fih_headsethook.kl:system/usr/keylayout/fih_headsethook.kl \
    vendor/motorola/triumph/proprietary/usr/keylayout/fih_ringswitch.kl:system/usr/keylayout/fih_ringswitch.kl \
    vendor/motorola/triumph/proprietary/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
    vendor/motorola/triumph/proprietary/usr/keylayout/bi041p.kl:system/usr/keylayout/bi041p.kl \
    vendor/motorola/triumph/proprietary/usr/keylayout/fbx_kybd.kl:system/usr/keylayout/fbx_kybd.kl \
    vendor/motorola/triumph/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
    vendor/motorola/triumph/proprietary/usr/keylayout/7k_handset.kl:system/usr/keylayout/7k_handset.kl \
    vendor/motorola/triumph/proprietary/usr/keylayout/surf_keypad.kl:system/usr/keylayout/surf_keypad.kl \
    vendor/motorola/triumph/proprietary/usr/keylayout/Vendor_2378_Product_100a.kl:system/usr/keylayout/Vendor_2378_Product_100a.kl

# Common 7x30 firmware
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/etc/firmware/vidc_720p_command_control.fw:system/etc/firmware/vidc_720p_command_control.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/vidc_720p_h263_dec_mc.fw:system/etc/firmware/vidc_720p_h263_dec_mc.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/vidc_720p_h264_dec_mc.fw:system/etc/firmware/vidc_720p_h264_dec_mc.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/vidc_720p_h264_enc_mc.fw:system/etc/firmware/vidc_720p_h264_enc_mc.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/vidc_720p_mp4_dec_mc.fw:system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/vidc_720p_mp4_enc_mc.fw:system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
    vendor/motorola/triumph/proprietary/etc/firmware/vidc_720p_vc1_dec_mc.fw:system/etc/firmware/vidc_720p_vc1_dec_mc.fw

# Triumph Prebuilt Files
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/etc/loc_parameter.ini:system/etc/loc_parameter.ini \
    vendor/motorola/triumph/proprietary/etc/gps.conf:/system/etc/gps.conf \
    vendor/motorola/triumph/proprietary/etc/SuplRootCert:/system/etc/SuplRootCert \
    vendor/motorola/triumph/proprietary/etc/apns-conf.xml:system/etc/apns-conf.xml \
    vendor/motorola/triumph/proprietary/usr/idc/bi041p.idc:/system/usr/idc/bi041p.idc \
    vendor/motorola/triumph/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml

# Wifi/Modules
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/lib/modules/libra.ko:/system/lib/modules/libra.ko \
    vendor/motorola/triumph/proprietary/lib/modules/libra_ftm.ko:/system/lib/modules/libra_ftm.ko \
    vendor/motorola/triumph/proprietary/etc/firmware/wlan/qcom_fw.bin:/system/etc/firmware/wlan/qcom_fw.bin \
    vendor/motorola/triumph/proprietary/etc/firmware/wlan/qcom_wapi_fw.bin:/system/etc/firmware/wlan/qcom_wapi_fw.bin \
    vendor/motorola/triumph/proprietary/etc/firmware/wlan/qcom_wlan_nv.bin:/system/etc/firmware/wlan/qcom_wlan_nv.bin \
    vendor/motorola/triumph/proprietary/etc/firmware/wlan/cfg.dat:/system/etc/firmware/wlan/cfg.dat \
    vendor/motorola/triumph/proprietary/etc/firmware/wlan/hostapd_default.conf:/system/etc/firmware/wlan/hostapd_default.conf \
    vendor/motorola/triumph/proprietary/etc/firmware/wlan/qcom_cfg.ini:/system/etc/firmware/wlan/qcom_cfg.ini \
    vendor/motorola/triumph/proprietary/etc/wifi/wpa_supplicant.conf:/system/etc/wifi/wpa_supplicant.conf \
    vendor/motorola/triumph/proprietary/etc/wifi/cert_chmod.sh:/system/etc/wifi/cert_chmod.sh

